### ISSUE TITLE
Documentation: IIIF Presentation module

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/IiifPresentation#1]
This module needs documentation. You can crib docs entirely from the [README](https://github.com/omeka-s-modules/IiifPresentation/blob/main/README.md).

**Comment by allanaaa** [comment]
This is ready to be looked at:

https://github.com/omeka/omeka-s-enduser/blob/305a8a03826541d3d10cc55f679091766cb61e1c/docs/modules/iiifpresentation.md

**Comment by jimsafley** [comment]
Looks good to me
