### ISSUE TITLE
Viewer menu duplicates

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/IiifPresentation#2]
I think this might be an issue with the Mirador code and not our own implementation, but I thought I'd mention it here just in case:

![mirador](https://user-images.githubusercontent.com/28012148/205703009-82c99544-4759-4f5a-a7d7-801e2153b54d.gif)

Loading multiple items, then popping out the item list, doesn't seem to check for redundancy and will just open endless new menus. I think it should probably check to see if it's already open and then toggle it off if so.

(I'm not clear if the Mirador viewer is part of this module or is shipping in the core code now?)

**Comment by jimsafley** [comment]
It's a quirk of Mirador. You could [open an issue with them](https://github.com/ProjectMirador/mirador/issues), but I'm not sure it's worth your time. It has a such minor impact on user experience, imo.

The Mirador viewer ships with the core code, not this module.
